# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4b3cb1327c82e75d4089fce2eba14009c920a60e4a5d7c08cea4f1b88a5511b5fdf989f8211e0e46f2b8291de93b5f0a46458d543b135bede02ebe29515d66c

test:
  secret_key_base: ea4af8f7bfccbed2541c48676b72e3bf2d6aefa7678e2efaa9fa7e5123512f2135c3ad52d5f2589a503f6b7024f7fa0c846e0bd7935f8511d980edb15afde9b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
